"""create api versions table

Revision ID: 009cf07ef2dd
Revises: 74e63190db7a
Create Date: 2026-09-14 15:42:15.258630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009cf07ef2dd'
down_revision: Union[str, Sequence[str], None] = '74e63190db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mock_api_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mock_api_id'], ['mock_apis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_api_id', 'version', name='uq_api_version_mock_api_version')
    )
    op.create_index(op.f('ix_api_versions_mock_api_id'), 'api_versions', ['mock_api_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_versions_mock_api_id'), table_name='api_versions')
    op.drop_table('api_versions')
    # ### end Alembic commands ###
