"""create request logs table

Revision ID: 1eb267db3e24
Revises: db0af566ea67
Create Date: 2026-09-15 10:42:24.830259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb267db3e24'
down_revision: Union[str, Sequence[str], None] = 'db0af566ea67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mock_api_id', sa.Integer(), nullable=False),
    sa.Column('api_version_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('path_params', sa.JSON(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ),
    sa.ForeignKeyConstraint(['mock_api_id'], ['mock_apis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_api_version_id'), 'request_logs', ['api_version_id'], unique=False)
    op.create_index(op.f('ix_request_logs_mock_api_id'), 'request_logs', ['mock_api_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_mock_api_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_api_version_id'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
