"""create response templates table

Revision ID: 9caea997135c
Revises: faca4167b052
Create Date: 2026-09-14 19:09:06.610400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caea997135c'
down_revision: Union[str, Sequence[str], None] = 'faca4167b052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_version_id', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_version_id', name='uq_response_template_api_version')
    )
    op.create_index(op.f('ix_response_templates_api_version_id'), 'response_templates', ['api_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_templates_api_version_id'), table_name='response_templates')
    op.drop_table('response_templates')
    # ### end Alembic commands ###
