"""create response scenarios table

Revision ID: a162ef67c6f9
Revises: 9caea997135c
Create Date: 2026-09-15 06:01:48.804250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a162ef67c6f9'
down_revision: Union[str, Sequence[str], None] = '9caea997135c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('delay_ms', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_scenarios_api_version_id'), 'response_scenarios', ['api_version_id'], unique=False)
    op.create_index(op.f('ix_response_scenarios_scenario_type'), 'response_scenarios', ['scenario_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_scenarios_scenario_type'), table_name='response_scenarios')
    op.drop_index(op.f('ix_response_scenarios_api_version_id'), table_name='response_scenarios')
    op.drop_table('response_scenarios')
    # ### end Alembic commands ###
