"""make request log api references nullable

Revision ID: d1f1cddba70a
Revises: 1eb267db3e24
Create Date: 2026-09-15 11:21:31.281034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1f1cddba70a'
down_revision: Union[str, Sequence[str], None] = '1eb267db3e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_logs', 'mock_api_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('request_logs', 'api_version_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_logs', 'api_version_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('request_logs', 'mock_api_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
