"""add requires auth to mock apis

Revision ID: db0af566ea67
Revises: a162ef67c6f9
Create Date: 2026-09-15 07:44:26.217968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0af566ea67'
down_revision: Union[str, Sequence[str], None] = 'a162ef67c6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_apis', sa.Column('requires_auth', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_apis', 'requires_auth')
    # ### end Alembic commands ###
