"""create request schemas table

Revision ID: faca4167b052
Revises: 009cf07ef2dd
Create Date: 2026-09-14 18:28:34.823322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faca4167b052'
down_revision: Union[str, Sequence[str], None] = '009cf07ef2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_version_id', sa.Integer(), nullable=False),
    sa.Column('body_schema', sa.JSON(), nullable=True),
    sa.Column('query_schema', sa.JSON(), nullable=True),
    sa.Column('path_schema', sa.JSON(), nullable=True),
    sa.Column('header_schema', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_version_id', name='uq_request_schema_api_version')
    )
    op.create_index(op.f('ix_request_schemas_api_version_id'), 'request_schemas', ['api_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_schemas_api_version_id'), table_name='request_schemas')
    op.drop_table('request_schemas')
    # ### end Alembic commands ###
